### ISSUE TITLE
ModuleNotFoundError: No module named 'mmtrack.models.sot'

### ISSUE THREAD

**Issue by Big-Rabbit-Ear** [VisDrone/Multi-Drone-Multi-Object-Detection-and-Tracking#6]

**Comment by origin-6** [comment]
How do you solve it?

**Comment by origin-6** [comment]
![image](https://github.com/user-attachments/assets/e9ff2726-1a4d-4582-a6fe-5986cf97f1ff)

**Comment by haohaoaaa66** [comment]
> ![image](https://github.com/user-attachments/assets/e9ff2726-1a4d-4582-a6fe-5986cf97f1ff)

Have you solved it yet？
